### ISSUE TITLE
Should we deprecate and remove this?

### ISSUE THREAD

**Issue by wesleytodd** [pkgjs/meet#144]
The initial goal here was to have something that was "repo driven" for meetings which could be used within and without the Node.js github org. Since it is not achieving that goal, and is not being used I wonder if it is time to retire it?

@mhdawson I guess as the maintainer of [create-node-meeting-artifacts](https://github.com/nodejs/create-node-meeting-artifacts), is there any interest in this package? Is there any way to abstract your tooling so that other folks outside of the node org could use it? Honestly when I looked at it I think [google-auth-wrapper](https://github.com/mhdawson/google-auth-wrapper) was my main concern, I don't think most projects want to maintain a calendar but if that tool was inverted I don't think folks would mind *having* a calendar be created from the repo source.  Anyway, maybe I am wrong on this since this repo never really seemed to gain traction for folks.

Anyway, so archive?

**Comment by mhdawson** [comment]
I would say archive. I don't have time to prioritize re-working what I have and it seems nobody else has cycles to work on it either.

**Comment by wesleytodd** [comment]
I will wait till next week to give folks a chance to disagree. But then will archive.

**Comment by wesleytodd** [comment]
We are seeing if there is a place for this as it was originally intended, for use with Express for planning and project management. Since we didn't archive I am going to continue working on it in here. If I get all the time and can start using it on Express then maybe it is still worth keeping alive.
