### ISSUE TITLE
Are the shorthands working?

### ISSUE THREAD

**Issue by bjohansebas** [pkgjs/meet#209]
I’m implementing the shorthand for #207, but I’ve been trying to get it to work and see it in action, and I notice that none of the shorthands are working. Is it my mistake, or is there an issue with the actions?

ref: https://github.com/bjohansebas/meet/issues/10, https://github.com/bjohansebas/meet/actions/runs/11964668332

**Comment by bjohansebas** [comment]
It seems like it's not performing the transformation correctly

![image](https://github.com/user-attachments/assets/50a17270-061c-414b-98b2-0dd9709fa45f)

**Comment by jonchurch** [comment]
Oh, I don't think so.

The `convert` function is not called anywhere in the code.

**Comment by jonchurch** [comment]
The code doesn't do token replacement on the default template

In your fork, you're relying on the default template.

try passing that same template to the `template` option
